name: Run ETL Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-etl:
    runs-on: ubuntu-latest  # Usa uma máquina Linux na nuvem

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          # Instalar pywin32 apenas no Windows, com a versão mais recente
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pip install pywin32  # Instala a versão mais recente compatível
          fi

      - name: Configurar API do Kaggle
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_BABOTELHO }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Executar pipeline ETL
        run: python etl_flow.py
